/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.io.File;
import java.util.ArrayList;
import java.util.Date;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.SwingUtilities;
import javax.swing.filechooser.FileNameExtensionFilter;
import javax.swing.table.DefaultTableModel;
import model.HDCT_CTSP;
import model.HoaDon;
import model.NhanVien;
import repository.HoaDonChiTietRepository;
import repository.HoaDonRepository;
import utilitys.ExcelHoaDon;

/**
 *
 * @author LENOVO
 */
public class jplHoaDon extends javax.swing.JPanel {

    /**
     * Creates new form jplHoaDon
     */
    private int soTrang = 1;
    private int page = 2;
    public ArrayList<HDCT_CTSP> hdctsp;
    private final HoaDonRepository hoaDonRepository = new HoaDonRepository();
    DefaultTableModel tblModel = new DefaultTableModel();
    private final HoaDonChiTietRepository hoaDonChiTietRepository = new HoaDonChiTietRepository();
    DefaultTableModel tblModel2 = new DefaultTableModel();
    public ArrayList<HoaDon> _lstHoaDon = hoaDonRepository.getAllHoaDon(soTrang);

    public jplHoaDon() {
        initComponents();
        tblModel = (DefaultTableModel) tblHoaDon.getModel();
        fillTable();
        tblModel2 = (DefaultTableModel) tblHoaDonChiTiet.getModel();
        jMenuItem1.setText("Xem chi tiết");
    }

    public void fillTable() {
        ArrayList<HoaDon> _lstHoaDon = hoaDonRepository.getAllHoaDon(soTrang);
        tblModel.setRowCount(0);
        String column[] = {"Mã Hóa Đơn", "Nhân Viên", "Khách Hàng", "Thành Tiền", "Khuyến Mãi", "Ghi Chú", "Ngày Tạo",  "Trạng Thái"};
        tblModel.setColumnIdentifiers(column);
        for (HoaDon hoaDon : _lstHoaDon) {
            tblModel.addRow(new Object[]{
                hoaDon.getMaHoaDon(), hoaDon.getIdNhanVien().getHoVaTen(), hoaDon.getIdKhachHang().getTenKhachHang()==null?"khach le*":hoaDon.getIdKhachHang().getTenKhachHang(), hoaDon.getThanhTien(), hoaDon.getIdKhuyenMai().getTenKhuyenMai(),  hoaDon.getGhiChu(), hoaDon.getNgayTao(), hoaDon.getTrangThai()
            });
        }
        lblHoaDon.setText(soTrang + "/" + SoBanGhiHoaDon());
        tblHoaDon.setModel(tblModel);
    }

    public int SoBanGhiHoaDon() {
        int soBanGhi;
        soBanGhi = hoaDonRepository.SoBanGhi();
        int tongTrang = soBanGhi / page;
        return tongTrang;
    }

    public int SoBanGhiHoaDonChiTiet() {
        int soBanGhi = hoaDonChiTietRepository.SoBanGhiHoaDonChiTiet();
        int tongTrang = soBanGhi / page;
        return tongTrang;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupHDCt = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        hoaDonChiTiet = new javax.swing.JDialog();
        lblMaHoaDon = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        maHoaDon = new javax.swing.JLabel();
        lblNgayTao = new javax.swing.JLabel();
        lblTenKhachHang = new javax.swing.JLabel();
        lblNhanVien = new javax.swing.JLabel();
        lblTongTien = new javax.swing.JLabel();
        lblPhieuGiamGia = new javax.swing.JLabel();
        lblSoTienGiam = new javax.swing.JLabel();
        lblKhachPhaiTra = new javax.swing.JLabel();
        TienKhachDua = new javax.swing.JLabel();
        lblTienThua = new javax.swing.JLabel();
        lblHinhThucThanhToan = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        lblNgayThanhToan = new javax.swing.JLabel();
        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        txtTimKiem = new javax.swing.JTextField();
        jPanel5 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        btnLoc = new javax.swing.JButton();
        btnXoa = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtTuNgay = new com.toedter.calendar.JDateChooser();
        txtDenNgay = new com.toedter.calendar.JDateChooser();
        cboNgayTao = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblHoaDon = new javax.swing.JTable();
        lblHoaDon = new javax.swing.JLabel();
        btnPrHoaDon = new javax.swing.JButton();
        btnNextHoaDon = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblHoaDonChiTiet = new javax.swing.JTable();
        lbHoaDonChiTiet = new javax.swing.JLabel();
        btnPrHoaDonChiTiet = new javax.swing.JButton();
        btnNextHoaDonChiTiet = new javax.swing.JButton();
        btnInExcel = new javax.swing.JButton();

        jMenuItem1.setText("jMenuItem1");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        popupHDCt.add(jMenuItem1);

        lblMaHoaDon.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("HÓA ĐƠN CHI TIẾT");

        jLabel8.setText("Ngày tạo:");

        jLabel10.setText("Tên khách hàng:");

        jLabel11.setText("Nhân viên:");

        jLabel12.setText("Phiếu giảm giá:");

        jLabel13.setText("Số tiền giảm được:");

        jLabel14.setText("Mã hóa đơn:");

        jLabel15.setText("Khách phải trả:");

        jLabel16.setText("Tiền khách đưa:");

        jLabel17.setText("Tổng tiền:");

        jLabel19.setText("Tiền thừa:");

        jLabel24.setText("Hình thức thanh toán:");

        maHoaDon.setText("jLabel9");

        lblNgayTao.setText("jLabel20");

        lblTenKhachHang.setText("jLabel21");

        lblNhanVien.setText("jLabel22");

        lblTongTien.setText("jLabel23");

        lblPhieuGiamGia.setText("jLabel25");

        lblSoTienGiam.setText("jLabel26");

        lblKhachPhaiTra.setText("jLabel27");

        TienKhachDua.setText("jLabel28");

        lblTienThua.setText("jLabel29");

        lblHinhThucThanhToan.setText("jLabel30");

        jLabel9.setText("Ngày thanh toán:");

        lblNgayThanhToan.setText("jLabel18");

        javax.swing.GroupLayout lblMaHoaDonLayout = new javax.swing.GroupLayout(lblMaHoaDon);
        lblMaHoaDon.setLayout(lblMaHoaDonLayout);
        lblMaHoaDonLayout.setHorizontalGroup(
            lblMaHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblMaHoaDonLayout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(lblMaHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, lblMaHoaDonLayout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addGroup(lblMaHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lblMaHoaDonLayout.createSequentialGroup()
                                .addGroup(lblMaHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel14))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(lblMaHoaDonLayout.createSequentialGroup()
                                .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, 110, Short.MAX_VALUE)
                                .addGap(73, 73, 73)))
                        .addGroup(lblMaHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(lblMaHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(maHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(lblNgayTao, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblNgayThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(lblMaHoaDonLayout.createSequentialGroup()
                        .addGroup(lblMaHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel12, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 92, Short.MAX_VALUE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(lblMaHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lblTenKhachHang, javax.swing.GroupLayout.DEFAULT_SIZE, 103, Short.MAX_VALUE)
                            .addComponent(lblNhanVien, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblPhieuGiamGia, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(lblMaHoaDonLayout.createSequentialGroup()
                        .addComponent(jLabel24, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblHinhThucThanhToan, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lblMaHoaDonLayout.createSequentialGroup()
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(lblMaHoaDonLayout.createSequentialGroup()
                        .addComponent(jLabel17, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblTongTien, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lblMaHoaDonLayout.createSequentialGroup()
                        .addGroup(lblMaHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel13, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(jLabel19, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(lblMaHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblSoTienGiam, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblTienThua, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(lblMaHoaDonLayout.createSequentialGroup()
                        .addComponent(jLabel15)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(lblKhachPhaiTra, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(lblMaHoaDonLayout.createSequentialGroup()
                        .addComponent(jLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(TienKhachDua, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, lblMaHoaDonLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel7)
                .addGap(92, 92, 92))
        );
        lblMaHoaDonLayout.setVerticalGroup(
            lblMaHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(lblMaHoaDonLayout.createSequentialGroup()
                .addComponent(jLabel7)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(lblMaHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(maHoaDon))
                .addGap(18, 18, 18)
                .addGroup(lblMaHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(lblNgayTao))
                .addGap(21, 21, 21)
                .addGroup(lblMaHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(lblNgayThanhToan))
                .addGap(18, 18, 18)
                .addGroup(lblMaHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(lblTenKhachHang))
                .addGap(19, 19, 19)
                .addGroup(lblMaHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(lblNhanVien))
                .addGap(24, 24, 24)
                .addGroup(lblMaHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(lblTongTien))
                .addGap(21, 21, 21)
                .addGroup(lblMaHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(lblPhieuGiamGia))
                .addGap(18, 18, 18)
                .addGroup(lblMaHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(lblSoTienGiam))
                .addGap(18, 18, 18)
                .addGroup(lblMaHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(lblKhachPhaiTra))
                .addGap(18, 18, 18)
                .addGroup(lblMaHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(TienKhachDua))
                .addGap(18, 18, 18)
                .addGroup(lblMaHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel19)
                    .addComponent(lblTienThua))
                .addGap(21, 21, 21)
                .addGroup(lblMaHoaDonLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel24)
                    .addComponent(lblHinhThucThanhToan))
                .addGap(21, 21, 21))
        );

        javax.swing.GroupLayout hoaDonChiTietLayout = new javax.swing.GroupLayout(hoaDonChiTiet.getContentPane());
        hoaDonChiTiet.getContentPane().setLayout(hoaDonChiTietLayout);
        hoaDonChiTietLayout.setHorizontalGroup(
            hoaDonChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hoaDonChiTietLayout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addComponent(lblMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );
        hoaDonChiTietLayout.setVerticalGroup(
            hoaDonChiTietLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, hoaDonChiTietLayout.createSequentialGroup()
                .addGap(0, 12, Short.MAX_VALUE)
                .addComponent(lblMaHoaDon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setBackground(new java.awt.Color(204, 255, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Hóa Đơn");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(65, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(1027, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Chức Năng", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Tìm Kiếm :");

        txtTimKiem.setBackground(new java.awt.Color(255, 255, 51));
        txtTimKiem.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtTimKiemCaretUpdate(evt);
            }
        });
        txtTimKiem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTimKiemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Lọc Theo Ngày");

        btnLoc.setBackground(new java.awt.Color(102, 102, 255));
        btnLoc.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnLoc.setText("Lọc");
        btnLoc.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnLoc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLocActionPerformed(evt);
            }
        });

        btnXoa.setBackground(new java.awt.Color(102, 102, 255));
        btnXoa.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        btnXoa.setText("Xóa Lọc");
        btnXoa.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        btnXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnXoaActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Từ");

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Đến");

        txtTuNgay.setBackground(new java.awt.Color(255, 255, 51));
        txtTuNgay.setDateFormatString("yyyy-MM-dd");

        txtDenNgay.setBackground(new java.awt.Color(255, 255, 51));
        txtDenNgay.setDateFormatString("yyyy-MM-dd");

        cboNgayTao.setBackground(new java.awt.Color(255, 255, 51));
        cboNgayTao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Ngày tạo", "Ngày thanh toán" }));
        cboNgayTao.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cboNgayTaoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLoc, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addComponent(cboNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(42, 42, 42)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnXoa)
                    .addComponent(txtDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnLoc)
                        .addComponent(btnXoa)))
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel5)
                        .addComponent(cboNgayTao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(txtTuNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDenNgay, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(15, Short.MAX_VALUE))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hóa Đơn", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tblHoaDon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Mã Hóa Đơn", "ID NV", "ID KHÁCH HÀNG", "ID KHUYẾN MÃI", "MÃ HÓA ĐƠN", "NGÀY MUA", "THÀNH TIỀN", "NGAY TẠO", "TRẠNG THÁ", "GHI CHÚ"
            }
        ));
        tblHoaDon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblHoaDonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblHoaDon);

        lblHoaDon.setText("jLabel7");

        btnPrHoaDon.setText("Pr");
        btnPrHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPrHoaDonActionPerformed(evt);
            }
        });

        btnNextHoaDon.setText("Next");
        btnNextHoaDon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNextHoaDonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1253, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(btnPrHoaDon)
                .addGap(37, 37, 37)
                .addComponent(lblHoaDon)
                .addGap(48, 48, 48)
                .addComponent(btnNextHoaDon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(19, 19, 19)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblHoaDon)
                    .addComponent(btnPrHoaDon)
                    .addComponent(btnNextHoaDon))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Hóa Đơn Chi Tiết", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Segoe UI", 1, 14))); // NOI18N

        tblHoaDonChiTiet.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "MÃ HÓA ĐƠN", "TÊN SẢN P HẨM", "HÃNG", "SIZE", "DANH MỤC", "CHẤT LIỆU", "MÀU", "SỐ LƯỢNG", "ĐƠN GIÁ", "NGÀY BÁN"
            }
        ));
        jScrollPane2.setViewportView(tblHoaDonChiTiet);

        lbHoaDonChiTiet.setText("jLabel7");

        btnPrHoaDonChiTiet.setText("Pr");

        btnNextHoaDonChiTiet.setText("Next");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2))
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addComponent(btnPrHoaDonChiTiet)
                .addGap(37, 37, 37)
                .addComponent(lbHoaDonChiTiet)
                .addGap(48, 48, 48)
                .addComponent(btnNextHoaDonChiTiet)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel8Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 153, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbHoaDonChiTiet)
                    .addComponent(btnPrHoaDonChiTiet)
                    .addComponent(btnNextHoaDonChiTiet))
                .addGap(210, 210, 210))
        );

        btnInExcel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utility/icon/Fax.png"))); // NOI18N
        btnInExcel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInExcelActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(18, 18, 18)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(29, 29, 29)
                        .addComponent(btnInExcel, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(15, 15, 15))
                    .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap(22, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnInExcel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        hoaDonChiTiet.setSize(420, 540);
        hoaDonChiTiet.setResizable(false);
        hoaDonChiTiet.setLocationRelativeTo(null);
        hoaDonChiTiet.setVisible(true);
        int selectRow = tblHoaDon.getSelectedRow();

        String idHoaDon = _lstHoaDon.get(selectRow).getId();
        HoaDon hd = hoaDonRepository.getHoaDonById(idHoaDon);
        maHoaDon.setText(hd.getMaHoaDon());
        lblNgayTao.setText(hd.getNgayTao().toString());
        lblNgayThanhToan.setText(hd.getNgayMua().toString());
        lblTenKhachHang.setText(hd.getIdKhachHang().getTenKhachHang());
        lblNhanVien.setText(hd.getIdNhanVien().getHoVaTen());
        System.out.println("" + hd.getIdNhanVien().getHoVaTen());
        lblPhieuGiamGia.setText(hd.getIdKhuyenMai().getTenKhuyenMai());
        lblTongTien.setText(String.valueOf(hd.getThanhTien()));
        Double tienGiam;
        if (hd.getIdKhuyenMai().getHinhThucApDung() == true) {
            tienGiam = (hd.getIdKhuyenMai().getGiaTri().doubleValue() * hd.getThanhTien().doubleValue()) / 100;
            lblSoTienGiam.setText(String.valueOf(tienGiam));
            Double tienKhachPhaiTra = hd.getThanhTien().doubleValue() - tienGiam;
            lblKhachPhaiTra.setText(String.valueOf(tienKhachPhaiTra));
            lblTienThua.setText(String.valueOf(hd.getTienThua()));

        } else {
            tienGiam = hd.getIdKhuyenMai().getGiaTri().doubleValue();
            lblSoTienGiam.setText(String.valueOf(tienGiam));
            Double tienKhachTra = hd.getThanhTien().doubleValue() - tienGiam;
            Double tienThua = tienKhachTra - tienKhachTra;
            lblKhachPhaiTra.setText(String.valueOf(tienKhachTra));
            lblTienThua.setText(String.valueOf(hd.getTienThua()));
        }
        TienKhachDua.setText(String.valueOf(hd.getTienKhachDua()));
        lblHinhThucThanhToan.setText(hd.getIdKhuyenMai().getHinhThucApDung() == true ? "Giảm theo %" : "Giảm theo tiền");
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void tblHoaDonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblHoaDonMouseClicked
        // TODO add your handling code here:
        if (SwingUtilities.isRightMouseButton(evt)) {
            int row = tblHoaDon.rowAtPoint(evt.getPoint());
            if (row >= 0) {
                tblHoaDon.setRowSelectionInterval(row, row);
                popupHDCt.show(evt.getComponent(), evt.getX(), evt.getY());
            }
        } else {
            int selectedRow = tblHoaDon.getSelectedRow();
            ArrayList<HoaDon> _lstHoaDon = hoaDonRepository.getAllHoaDon(soTrang);
            String idHoaDon = _lstHoaDon.get(selectedRow).getId();
            fillTable2(idHoaDon);
            ArrayList<HDCT_CTSP> hdctsp = hoaDonChiTietRepository.getByIdHoaDon(idHoaDon);
            if (selectedRow < 0 || selectedRow > hdctsp.size()) {
                return;
            }
        }
    }//GEN-LAST:event_tblHoaDonMouseClicked

    private void txtTimKiemCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtTimKiemCaretUpdate
        // TODO add your handling code here:
        String keyword = txtTimKiem.getText().trim();
        if (!keyword.equals("")) {
            ArrayList<HoaDon> _lstHoaDon = hoaDonRepository.searchHoaDon(keyword);
            tblModel.setRowCount(0);
            String column[] = {"Mã Hóa Đơn", "Nhân Viên", "Khách Hàng", "Thành Tiền", "Khuyến Mãi", "Ghi Chú", "Ngày Tạo", "Trạng Thái"};
            tblModel.setColumnIdentifiers(column);
            for (HoaDon hoaDon : _lstHoaDon) {
                tblModel.addRow(new Object[]{
                    hoaDon.getMaHoaDon(), hoaDon.getIdNhanVien().getHoVaTen(), hoaDon.getIdKhachHang().getTenKhachHang(), hoaDon.getThanhTien(), hoaDon.getIdKhuyenMai().getTenKhuyenMai(), hoaDon.getGhiChu(), hoaDon.getNgayTao(),  hoaDon.getTrangThai()
                });
            }
            tblHoaDon.setModel(tblModel);
        } else {
            fillTable();
        }
    }//GEN-LAST:event_txtTimKiemCaretUpdate

    private void btnXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnXoaActionPerformed
        // TODO add your handling code here:
        cboNgayTao.setSelectedItem(0);
        txtDenNgay.setDate(null);
        txtTuNgay.setDate(null);
        txtTimKiem.setText(null);
        fillTable();
    }//GEN-LAST:event_btnXoaActionPerformed

    private void btnLocActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLocActionPerformed
        // TODO add your handling code here:
        Date ngayBatDau = txtTuNgay.getDate();
        Date ngayKetThuc = txtDenNgay.getDate();

        if (ngayBatDau != null && ngayKetThuc != null) {
            long khoangCach = ngayKetThuc.getTime() - ngayBatDau.getTime();
            long soNgay = khoangCach / (24 * 60 * 60 * 1000); // Chuyển đổi sang số ngày

            if (soNgay > 30) {
                JOptionPane.showMessageDialog(this, "Khoảng cách giữa ngày bắt đầu và ngày kết thúc không được lớn hơn 30 ngày", "Thông báo", JOptionPane.WARNING_MESSAGE);
                return;
            }
        } else {
            JOptionPane.showMessageDialog(this, "Vui lòng chọn cả ngày bắt đầu và ngày kết thúc", "Thông báo", JOptionPane.WARNING_MESSAGE);
            return;
        }

        if (ngayBatDau == null) {
            JOptionPane.showMessageDialog(this, "Ngày bắt đầu không được để trống");
            return;
        }
        if (ngayKetThuc == null) {
            JOptionPane.showMessageDialog(this, "Ngày kết thúc không được để trống");
            return;
        }
        if (ngayBatDau.getTime() > ngayKetThuc.getTime()) {
            JOptionPane.showMessageDialog(this, "Ngày bắt đầu phải nhỏ hơn ngày kết thúc");
            return;
        }

        String kieuNgay = (String) cboNgayTao.getSelectedItem();
        if (kieuNgay.equals("Ngày tạo")) {
            kieuNgay = "NgayTao";
        } else if (kieuNgay.equals("Ngày thanh toán")) {
            kieuNgay = "NgayMua";
        }
        ArrayList<HoaDon> newHoaDon = hoaDonRepository.getHoaDonByDate(ngayKetThuc, ngayBatDau, kieuNgay);
        tblModel.setRowCount(0);
        String column[] = {"Mã Hóa Đơn", "Nhân Viên", "Khách Hàng", "Thành Tiền", "Khuyến Mãi", "Ghi Chú", "Ngày Mua", "Ngày Tạo", "Trạng Thái"};
        tblModel.setColumnIdentifiers(column);
        for (HoaDon hoaDon : newHoaDon) {
            tblModel.addRow(new Object[]{
                hoaDon.getMaHoaDon(), hoaDon.getIdNhanVien().getHoVaTen(), hoaDon.getIdKhachHang().getTenKhachHang(), hoaDon.getThanhTien(), hoaDon.getIdKhuyenMai().getTenKhuyenMai(), hoaDon.getGhiChu(), hoaDon.getNgayMua(), hoaDon.getNgayTao(),hoaDon.getTrangThai()
            });
        }
        tblHoaDon.setModel(tblModel);
    }//GEN-LAST:event_btnLocActionPerformed

    private void btnNextHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNextHoaDonActionPerformed
        // TODO add your handling code here:

        if (soTrang < SoBanGhiHoaDon()) {
            soTrang++;
            fillTable();
            lblHoaDon.setText(soTrang + "/" + SoBanGhiHoaDon());
        }
    }//GEN-LAST:event_btnNextHoaDonActionPerformed

    public void fillTable2(String idHoaDon) {

        ArrayList<HDCT_CTSP> _listHDCT = hoaDonChiTietRepository.getByIdHoaDon(idHoaDon);
        tblModel2.setRowCount(0);
        String column2[] = {
            "Mã hóa đơn", "Tên Sản phẩm", "Hãng", "Size", "Danh mục", "Chất liệu", "Màu",  "Số lượng", "Đơn giá", "Ngày Bán"
        };
        tblModel2.setColumnIdentifiers(column2);
        for (HDCT_CTSP HDCT : _listHDCT) {

            tblModel2.addRow(new Object[]{
                HDCT.getMaHoaDon(), HDCT.getTenSanPham(), HDCT.getTenHang(), HDCT.getSize(), HDCT.getTenDanhMuc(), HDCT.getChatLieu(), HDCT.getMauSac(), HDCT.getSoLuong(), HDCT.getDonGia(), HDCT.getNgayBan()
            });
        }
        tblHoaDonChiTiet.setModel(tblModel2);
        lbHoaDonChiTiet.setText(soTrang + "/" + SoBanGhiHoaDonChiTiet());
    }
    private void btnPrHoaDonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPrHoaDonActionPerformed
        // TODO add your handling code here:
        if (soTrang > 1) {
            soTrang--;
            fillTable();
            lblHoaDon.setText(soTrang + "/" + SoBanGhiHoaDon());
        }
    }//GEN-LAST:event_btnPrHoaDonActionPerformed

    private void cboNgayTaoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cboNgayTaoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cboNgayTaoActionPerformed

    private void btnInExcelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInExcelActionPerformed
//         TODO add your handling code here:
        int selected = tblHoaDon.getSelectedRow();
        ArrayList<HoaDon> lstHoaDon = hoaDonRepository.getAllHoaDon(soTrang);
        if (selected >= 0) {
            HoaDon hd = lstHoaDon.get(selected);

            int confirm = JOptionPane.showConfirmDialog(this, "Bạn có muốn in hóa đơn " + hd.getMaHoaDon() + " không?");
            if (confirm == JOptionPane.YES_OPTION) {
                JFileChooser chooser = new JFileChooser("D:\\");
                chooser.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
                FileNameExtensionFilter avatarFilter = new FileNameExtensionFilter("Exel File", "xlsx");
                chooser.setFileFilter(avatarFilter);
                chooser.setAcceptAllFileFilterUsed(false);
                int selectFileCheck = chooser.showOpenDialog(this);
                File selectedFile = chooser.getSelectedFile();
                if (!(selectFileCheck == JFileChooser.APPROVE_OPTION)) {
                    return;
                }
                String path = selectedFile.getAbsolutePath();
                ExcelHoaDon export = new ExcelHoaDon();
                try {
                    HoaDon hoaDon = hoaDonRepository.getHoaDonById(hd.getId());
                    ArrayList<HDCT_CTSP> hdct_ctsps = hoaDonChiTietRepository.getByIdHoaDon(hd.getId());
                
                    export.inHoaDon(hoaDon, hdct_ctsps, path);
                    JOptionPane.showMessageDialog(this, "In hóa đơn thành công");

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "In hóa đơn thất bại");
                }
            }
}
    }//GEN-LAST:event_btnInExcelActionPerformed

    private void txtTimKiemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTimKiemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTimKiemActionPerformed
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel TienKhachDua;
    private javax.swing.JButton btnInExcel;
    private javax.swing.JButton btnLoc;
    private javax.swing.JButton btnNextHoaDon;
    private javax.swing.JButton btnNextHoaDonChiTiet;
    private javax.swing.JButton btnPrHoaDon;
    private javax.swing.JButton btnPrHoaDonChiTiet;
    private javax.swing.JButton btnXoa;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JComboBox<String> cboNgayTao;
    private javax.swing.JDialog hoaDonChiTiet;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lbHoaDonChiTiet;
    private javax.swing.JLabel lblHinhThucThanhToan;
    private javax.swing.JLabel lblHoaDon;
    private javax.swing.JLabel lblKhachPhaiTra;
    private javax.swing.JPanel lblMaHoaDon;
    private javax.swing.JLabel lblNgayTao;
    private javax.swing.JLabel lblNgayThanhToan;
    private javax.swing.JLabel lblNhanVien;
    private javax.swing.JLabel lblPhieuGiamGia;
    private javax.swing.JLabel lblSoTienGiam;
    private javax.swing.JLabel lblTenKhachHang;
    private javax.swing.JLabel lblTienThua;
    private javax.swing.JLabel lblTongTien;
    private javax.swing.JLabel maHoaDon;
    private javax.swing.JPopupMenu popupHDCt;
    private javax.swing.JTable tblHoaDon;
    private javax.swing.JTable tblHoaDonChiTiet;
    private com.toedter.calendar.JDateChooser txtDenNgay;
    private javax.swing.JTextField txtTimKiem;
    private com.toedter.calendar.JDateChooser txtTuNgay;
    // End of variables declaration//GEN-END:variables
}
