/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.math.BigDecimal;
import java.sql.Connection;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import model.HoaDonCho;
import model.KhuyenMai;
import repository.BanHangRepository;
import repository.HoadonChoRepository;
import repository.KhuyenMaiRepository;

/**
 *
 * @author acer
 */
public class jplHD_KM extends javax.swing.JFrame {
 KhuyenMaiRepository khuyenMaiRepository = new KhuyenMaiRepository();
 private final HoadonChoRepository hoadonChoRepository = new HoadonChoRepository();
    DefaultTableModel defaultTableModelGetKM;
    DefaultTableModel defaultTableModelCHL;
    DefaultTableModel dtmSP;
    DefaultTableModel dtmKM;
    DefaultTableModel defaultTableModel;
 
    ArrayList<HoaDonCho> hdc = hoadonChoRepository.getAllHoaDonCho();
    BanHangRepository banHangRepository;
    jplBanHang banHang;
    JTable tblHoaDon;
    
    Connection cn;
    long count, count1, soTrang, soTrang1, trang = 1, trang1 = 1;
    private int soTrang3 = 1;
    private int page = 2;
    public jplHD_KM(jplBanHang banHang,JTable tblHoaDon) {
        initComponents();
        loadDataTableKhuyenMaiCHL();
        pack(); // Điều chỉnh kích thước cửa sổ
        setLocationRelativeTo(null); // Đặt vị trí ở giữa màn hình
        this.banHang = banHang;
        this.tblHoaDon = tblHoaDon;
    }
        public int SoBanGhiKhuyenMaiCHL() {
        int soBanGhi;
        soBanGhi = khuyenMaiRepository.SoBanGhiKhuyenMaiHD();
        int tongTrang = soBanGhi / page;
        return tongTrang;
    }

    public int SoBanGhiKhuyenMaiHHL() {
        int soBanGhi;
        soBanGhi = khuyenMaiRepository.SoBanGhiKhuyenMaiNHD();
        int tongTrang = soBanGhi / page;
        return tongTrang;
    }

    public void loadDataTableKhuyenMaiCHL() {
        ArrayList<KhuyenMai> list = khuyenMaiRepository.getAllKhuyenMaiHoatDong(soTrang3);
        defaultTableModelCHL = (DefaultTableModel) tbl_KhuyenMai.getModel();
        defaultTableModelCHL.setRowCount(0);
        for (KhuyenMai km : list) {
            defaultTableModelCHL.addRow(new Object[]{
                km.getId(),
                km.getMaKhuyenMai(),
                km.getTenKhuyenMai(),
                km.getSoLuong(),
                km.getHinhThucApDung() == true ? "Giảm theo %" : "Giảm theo tiền",
                km.getGiaTri(),
                km.getDieuKienGiam(),
                km.getNgayBatDau(),
                km.getNgayKetThuc(),
                km.getTrangThai() == 1 ? "Còn Hiệu Lực" : "Hết Hạn",});
        }
        lb_trang.setText(soTrang3 + "/" + SoBanGhiKhuyenMaiCHL());
        tbl_KhuyenMai.setModel(defaultTableModelCHL);
    }

   
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_KhuyenMai = new javax.swing.JTable();
        btn_lon2 = new javax.swing.JButton();
        lb_trang = new javax.swing.JLabel();
        btn_nho2 = new javax.swing.JButton();
        btnChon = new javax.swing.JButton();
        txtTimKiem = new javax.swing.JTextField();
        btnTim = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tbl_KhuyenMai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Mã khuyến mại", "Tên chương trình", "Số Lượng", "Áp dụng", "Giá Trị", "DieuKienGiam", "Ngày bắt đầu", "Ngày kết thúc", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_KhuyenMai.setSelectionBackground(new java.awt.Color(153, 255, 153));
        tbl_KhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_KhuyenMaiMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_KhuyenMai);

        btn_lon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utility/icon/Right.png"))); // NOI18N
        btn_lon2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lon2ActionPerformed(evt);
            }
        });

        lb_trang.setText("jLabel9");

        btn_nho2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utility/icon/Left.png"))); // NOI18N
        btn_nho2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nho2ActionPerformed(evt);
            }
        });

        btnChon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utility/icon/Pointer.png"))); // NOI18N
        btnChon.setText("Chọn ");
        btnChon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnChonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(226, 226, 226)
                .addComponent(btn_nho2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_trang)
                .addGap(12, 12, 12)
                .addComponent(btn_lon2)
                .addGap(53, 53, 53)
                .addComponent(btnChon)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 877, Short.MAX_VALUE)
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(lb_trang, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btn_nho2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btn_lon2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnChon, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(12, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Còn Hiệu Lực", jPanel8);

        btnTim.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utility/icon/Zoom.png"))); // NOI18N
        btnTim.setText("Timkiem");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txtTimKiem, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnTim)
                .addGap(62, 62, 62))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnTim)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(4, 4, 4)
                        .addComponent(txtTimKiem)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(293, 293, 293))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, 343, Short.MAX_VALUE)
                .addGap(6, 6, 6))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_nho2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nho2ActionPerformed
        // TODO add your handling code here:
        if (soTrang3 > 1) {
            soTrang3--;
            loadDataTableKhuyenMaiCHL();
            lb_trang.setText(soTrang3 + "/" + SoBanGhiKhuyenMaiCHL());

        }
    }//GEN-LAST:event_btn_nho2ActionPerformed

    private void btn_lon2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lon2ActionPerformed
        // TODO add your handling code here:
        if (soTrang3 < SoBanGhiKhuyenMaiCHL()) {
            soTrang3++;
            loadDataTableKhuyenMaiCHL();
            lb_trang.setText(soTrang3 + "/" + SoBanGhiKhuyenMaiCHL());
        }
    }//GEN-LAST:event_btn_lon2ActionPerformed

    private void tbl_KhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_KhuyenMaiMouseClicked
        // TODO add your handling code here:
        int row = tbl_KhuyenMai.getSelectedRow();
        if (row < 0) {

            return;
        }
        
    }//GEN-LAST:event_tbl_KhuyenMaiMouseClicked

    private void btnChonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnChonActionPerformed
  int rowKM = tbl_KhuyenMai.getSelectedRow();
  if (rowKM < 0){
      JOptionPane.showMessageDialog(this, "Bạn phải chọn 1 dòng ");
} else {
    String idKM = tbl_KhuyenMai.getValueAt(rowKM, 0).toString();
    int rowHD = tblHoaDon.getSelectedRow();
    if (rowHD < 0) {
        JOptionPane.showMessageDialog(this, "Bạn phải chọn 1 dòng từ tblHoaDon");
    } else {
        String idHD = hdc.get(tblHoaDon.getSelectedRow()).getId();
        System.out.println(idHD);
         int cf = JOptionPane.showConfirmDialog(this,
                    "Bạn chắc chắn muốn thêm voucher này", "Thông báo", JOptionPane.YES_NO_OPTION);
            if (cf == JOptionPane.NO_OPTION) {
                return;
            }  // Đưa con trỏ đến dòng được chọn
            BigDecimal gtrigiam = new BigDecimal(tbl_KhuyenMai.getValueAt(rowKM, 6).toString());
            System.out.println(gtrigiam);
       if (banHang.tienHoaDon().compareTo(gtrigiam) <= 0) {
           JOptionPane.showMessageDialog(this, "Hóa đơn của bạn không đủ điều kiện để dùng voucher này \n"+
                                                "Hóa đơn của bạn phải trên "+gtrigiam
                                                );
         return;
}

        System.out.println(banHang.tienHoaDon());
       hoadonChoRepository.updateKhuyenMaiVaoHoaDonByID(idHD, idKM);
       JOptionPane.showMessageDialog(this, "Thêm thành công");
       banHang.loadDataToTableHoaDonCho();
       banHang.selectedRowInBanHang = rowHD;
       tblHoaDon.setRowSelectionInterval(banHang.selectedRowInBanHang, banHang.selectedRowInBanHang);
       banHang.showdetailHDC();
        this.dispose();
    }
}
        this.dispose();
    }//GEN-LAST:event_btnChonActionPerformed

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(jplHD_KM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(jplHD_KM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(jplHD_KM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(jplHD_KM.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new jplHD_KM().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnChon;
    private javax.swing.JButton btnTim;
    private javax.swing.JButton btn_lon2;
    private javax.swing.JButton btn_nho2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lb_trang;
    private javax.swing.JTable tbl_KhuyenMai;
    private javax.swing.JTextField txtTimKiem;
    // End of variables declaration//GEN-END:variables
}
