/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package view;

import java.math.BigDecimal;
import java.sql.Connection;
import java.util.Date;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.KhuyenMai;
import repository.KhuyenMaiRepository;
import service.KhuyenMaiService;
import utilitys.DBConnection;

/**
 *
 * @author Thuan
 */
public class jplKhuyenMai extends javax.swing.JPanel {

    /**
     * Creates new form jpl_KhuyenMai
     */
//    private KhuyenMaiService khuyenMaiService = new KhuyenMaiService();
    KhuyenMaiRepository khuyenMaiRepository = new KhuyenMaiRepository();
    DefaultTableModel defaultTableModelGetKM;
    DefaultTableModel defaultTableModelCHL;
    DefaultTableModel defaultTableModelHHL;
    DefaultTableModel dtmSP;
    DefaultTableModel dtmKM;

    Connection cn;
    long count, count1, soTrang, soTrang1, trang = 1, trang1 = 1;
    private int soTrang3 = 1;
    private int page = 4;

    public jplKhuyenMai() throws Exception {
        initComponents();
        loadDataTableKhuyenMaiCHL();
        loadDataTableKhuyenMaiHHL();

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    public int SoBanGhiKhuyenMaiCHL() {
        int soBanGhi;
        soBanGhi = khuyenMaiRepository.SoBanGhiKhuyenMaiHD();
        int tongTrang = soBanGhi / page;
        return tongTrang;
    }

    public int SoBanGhiKhuyenMaiHHL() {
        int soBanGhi;
        soBanGhi = khuyenMaiRepository.SoBanGhiKhuyenMaiNHD();
        int tongTrang = soBanGhi / page;
        return tongTrang;
    }

    public void loadDataTableKhuyenMaiCHL() {
        ArrayList<KhuyenMai> list = khuyenMaiRepository.getAllKhuyenMaiHoatDong(soTrang3);
        defaultTableModelCHL = (DefaultTableModel) tbl_KhuyenMai.getModel();
        defaultTableModelCHL.setRowCount(0);
        for (KhuyenMai km : list) {
            defaultTableModelCHL.addRow(new Object[]{
                km.getId(),
                km.getMaKhuyenMai(),
                km.getTenKhuyenMai(),
                km.getSoLuong(),
                km.getHinhThucApDung() == true ? "Giảm theo %" : "Giảm theo tiền",
                km.getGiaTri(),
                km.getDieuKienGiam(),
                km.getNgayBatDau(),
                km.getNgayKetThuc(),
                km.getTrangThai() == 1 ? "Còn Hiệu Lực" : "Hết Hạn",});
        }
        lb_trang.setText(soTrang3 + "/" + SoBanGhiKhuyenMaiCHL());
        tbl_KhuyenMai.setModel(defaultTableModelCHL);
    }

    public void loadDataTableKhuyenMaiHHL() {
        ArrayList<KhuyenMai> list = khuyenMaiRepository.getAllKhuyenMaiNgungHoatDong(soTrang3);
        defaultTableModelHHL = (DefaultTableModel) tbl_KhuyenMaiHHL.getModel();
        defaultTableModelHHL.setRowCount(0);
        for (KhuyenMai km : list) {
            defaultTableModelHHL.addRow(new Object[]{
                km.getId(),
                km.getMaKhuyenMai(),
                km.getTenKhuyenMai(),
                km.getSoLuong(),
                km.getHinhThucApDung() == true ? "Giảm theo %" : "Giảm theo tiền",
                km.getGiaTri(),
                km.getDieuKienGiam(),
                km.getNgayBatDau(),
                km.getNgayKetThuc(),
                km.getTrangThai() == 1 ? "Còn Hiệu Lực" : "Hết Hạn",});
        }
        lb_trang1.setText(soTrang3 + "/" + SoBanGhiKhuyenMaiCHL());
        tbl_KhuyenMaiHHL.setModel(defaultTableModelHHL);
    }

    public void lammoi() {
        txtMaKhuyenMai.setText("");
        txtTenKhuyenMai.setText("");
        txtBatDau.setDate(null);
        txtKetThuc.setDate(null);
        txtGiaTri.setText("");
        txtDieuKienGiam.setText("");
        txtSoLuong.setText("");
        cbbHinhThucGiamGia.setSelectedIndex(0);
    }

    private KhuyenMai KiemTraDuLieu() {
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yy HH:mm:ss");
        SimpleDateFormat sdf1 = new SimpleDateFormat("yyyy-MM-dd");
        Date date;
        String makm = txtMaKhuyenMai.getText().trim();
        String tenkm = txtTenKhuyenMai.getText().trim();
        Boolean hinhthuc = cbbHinhThucGiamGia.getSelectedIndex() == 0 ? true : false;
        BigDecimal giatri = null;
        BigDecimal dieuKienGiam = null;
        Date ngayBD = txtBatDau.getDate();
        Date ngayKT = txtKetThuc.getDate();
        java.util.Date NgayBatDau;
        java.util.Date NgayKetThuc;
//        int soLuong = Integer.parseInt(txtSoLuong.getText());
        String sl = txtSoLuong.getText();
        int soLuong = 0;
        int trangthai = 0;

        if (sl.trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Không được để trống số lượng");
            txtSoLuong.requestFocus();
            return null;
        }
        try {
            soLuong = Integer.valueOf(txtSoLuong.getText());
            if (soLuong < 0) {
                JOptionPane.showMessageDialog(this, "Số lượng không được âm");
                return null;
            }

        } catch (Exception e) {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Phải nhập vào là số");
            return null;
        }

        if (makm.length() == 0) {
            JOptionPane.showMessageDialog(this, "Không được để trống mã Khuyến Mại");
            return null;
        }

        if (tenkm.length() == 0) {
            JOptionPane.showMessageDialog(this, "Không được để trống tên Khuyến Mại");
            return null;
        }
        if (txtGiaTri.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Không được để trống giá trị");
            return null;
        } else {
            try {
                giatri = BigDecimal.valueOf(Double.parseDouble(txtGiaTri.getText()));

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "sai định dạng giá trị");
                e.printStackTrace();
            }
        }
        if (hinhthuc) { // Nếu hình thức giảm giá là theo phần trăm
            if (txtGiaTri.getText().trim().length() == 0) {
                JOptionPane.showMessageDialog(this, "Không được để trống giá trị");
                return null;
            } else {
                try {
                    int giaTriPhanTram = Integer.parseInt(txtGiaTri.getText());
//                    giatri = BigDecimal.valueOf(Double.parseDouble(txtGiaTri.getText()));
                    if (giaTriPhanTram < 1 || giaTriPhanTram > 100) {
                        JOptionPane.showMessageDialog(this, "Giá trị phần trăm phải từ 1 đến 100");
                        return null;
                    }
                } catch (NumberFormatException e) {
                    JOptionPane.showMessageDialog(this, "Sai định dạng giá trị phần trăm");
                    e.printStackTrace();
                    return null;
                }
            }
        }
        if (!hinhthuc) { // If the promotion is based on a fixed amount
            if (txtDieuKienGiam.getText().trim().length() == 0) {
                JOptionPane.showMessageDialog(this, "Không được để trống giảm tối đa");
                return null;
            } else {
                try {
                    dieuKienGiam = BigDecimal.valueOf(Double.parseDouble(txtDieuKienGiam.getText()));
                    // Check if txtDieuKienGiam is greater than txtGiaTri
                    if (dieuKienGiam.compareTo(giatri) <= 0) {
                        JOptionPane.showMessageDialog(this, "Điều kiện áp dụng phải lớn hơn giá trị");
                        return null;
                    }
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Sai định dạng điều kiện áp dụng");
                    e.printStackTrace();
                    return null;
                }
            }
        }

        if (txtDieuKienGiam.getText().trim().length() == 0) {
            JOptionPane.showMessageDialog(this, "Không được để trống điều kiện áp dụng");
            return null;
        } else {
            try {
                dieuKienGiam = BigDecimal.valueOf(Double.parseDouble(txtDieuKienGiam.getText()));

            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, "sai định dạng điều kiện áp dụng");
                e.printStackTrace();
            }
        }

        if (ngayBD == null) {
            JOptionPane.showMessageDialog(this, "Không được để trống ngày bắt đầu");
            txtBatDau.requestFocus();
            return null;
        } else {

            NgayBatDau = txtBatDau.getDate();
        }
        if (ngayKT == null) {
            JOptionPane.showMessageDialog(this, "Không được để trống ngày kết thúc");
            txtKetThuc.requestFocus();
            return null;
        } else {

            NgayKetThuc = txtKetThuc.getDate();
        }

        int compare = NgayBatDau.compareTo(NgayKetThuc);

        if (compare > 0) {
            JOptionPane.showMessageDialog(this, "ngày kết thúc phải sau ngày bắt đầu");
            return null;
        } else if (compare == 0) {
            JOptionPane.showMessageDialog(this, "ngày kết thúc phải sau ngày bắt đầu");
            return null;
        } else {

            NgayBatDau = txtBatDau.getDate();
            NgayKetThuc = txtKetThuc.getDate();

        }
        java.util.Date currentDate = new java.util.Date();

        if (currentDate.before(NgayKetThuc)) {
            trangthai = 0;
        } else if (currentDate.after(NgayKetThuc)) {
            trangthai = 1;
        }
        KhuyenMai khuyenMai = new KhuyenMai(makm, tenkm, giatri, dieuKienGiam, NgayBatDau, NgayKetThuc, soLuong, hinhthuc, trangthai);
        return khuyenMai;
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel7 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMaKhuyenMai = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtTenKhuyenMai = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbbHinhThucGiamGia = new javax.swing.JComboBox<>();
        txtGiaTri = new javax.swing.JTextField();
        txtDieuKienGiam = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        txtSoLuong = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtBatDau = new com.toedter.calendar.JDateChooser();
        txtKetThuc = new com.toedter.calendar.JDateChooser();
        btnLuu = new javax.swing.JButton();
        btnSua = new javax.swing.JButton();
        btnLamMOi = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel8 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbl_KhuyenMai = new javax.swing.JTable();
        btn_lon2 = new javax.swing.JButton();
        lb_trang = new javax.swing.JLabel();
        btn_nho2 = new javax.swing.JButton();
        jPanel9 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbl_KhuyenMaiHHL = new javax.swing.JTable();
        btn_nho3 = new javax.swing.JButton();
        lb_trang1 = new javax.swing.JLabel();
        btn_lon3 = new javax.swing.JButton();

        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanel5.setForeground(new java.awt.Color(102, 255, 102));

        jPanel1.setBackground(new java.awt.Color(255, 255, 102));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Tạo mã khuyến mãi");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("Tạo chương trình khuyến mãi");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Hình thức giảm giá");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Giá trị giảm");

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Điều kiện áp dụng");

        cbbHinhThucGiamGia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Giảm theo %", "Giảm theo tiền", " " }));
        cbbHinhThucGiamGia.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbbHinhThucGiamGiaActionPerformed(evt);
            }
        });

        txtGiaTri.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtGiaTriCaretUpdate(evt);
            }
        });

        jLabel9.setText("Số Lượng");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtSoLuong, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtMaKhuyenMai, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtTenKhuyenMai, javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(cbbHinhThucGiamGia, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGap(29, 29, 29)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtGiaTri, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(141, 141, 141)
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel5)
                                            .addComponent(txtDieuKienGiam, javax.swing.GroupLayout.PREFERRED_SIZE, 171, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                        .addGap(23, 23, 23))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtMaKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtTenKhuyenMai, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txtSoLuong, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbbHinhThucGiamGia)
                    .addComponent(txtGiaTri, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtDieuKienGiam, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel6.setBackground(new java.awt.Color(255, 255, 102));
        jPanel6.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jPanel2.setBackground(new java.awt.Color(255, 255, 102));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));

        jLabel6.setFont(new java.awt.Font("Segoe UI Black", 1, 14)); // NOI18N
        jLabel6.setText("Thời Gian Sử Dụng");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Thời Gian Bắt Đầu");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Thời Gian Kết Thúc");

        txtBatDau.setDateFormatString("yyyy-MM-dd");

        txtKetThuc.setDateFormatString("yyyy-MM-dd");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtKetThuc, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                        .addComponent(txtBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 212, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(64, 64, 64)
                        .addComponent(jLabel6)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap(32, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel6)
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtBatDau, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(23, 23, 23)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtKetThuc, javax.swing.GroupLayout.DEFAULT_SIZE, 33, Short.MAX_VALUE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(19, 19, 19))
        );

        btnLuu.setBackground(new java.awt.Color(204, 255, 255));
        btnLuu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utility/icon/Anchor.png"))); // NOI18N
        btnLuu.setText("Thêm");
        btnLuu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLuuActionPerformed(evt);
            }
        });

        btnSua.setBackground(new java.awt.Color(204, 255, 255));
        btnSua.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utility/icon/Refresh.png"))); // NOI18N
        btnSua.setText("Cập Nhật");
        btnSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuaActionPerformed(evt);
            }
        });

        btnLamMOi.setBackground(new java.awt.Color(204, 255, 255));
        btnLamMOi.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utility/icon/Thoat.png"))); // NOI18N
        btnLamMOi.setText("làm Mới");
        btnLamMOi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLamMOiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel6Layout.createSequentialGroup()
                        .addComponent(btnLuu, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(48, 48, 48)
                        .addComponent(btnSua)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnLamMOi)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnLuu)
                    .addComponent(btnSua)
                    .addComponent(btnLamMOi))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(29, 29, 29))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jPanel8.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tbl_KhuyenMai.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Mã khuyến mại", "Tên chương trình", "Số Lượng", "Áp dụng", "Giá trị", "Điều kiện giảm", "Ngày bắt đầu", "Ngày kết thúc", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_KhuyenMai.setSelectionBackground(new java.awt.Color(153, 255, 153));
        tbl_KhuyenMai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_KhuyenMaiMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbl_KhuyenMai);

        btn_lon2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utility/icon/Right.png"))); // NOI18N
        btn_lon2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lon2ActionPerformed(evt);
            }
        });

        lb_trang.setText("jLabel9");

        btn_nho2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utility/icon/Left.png"))); // NOI18N
        btn_nho2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nho2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 1052, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(268, 268, 268)
                .addComponent(btn_nho2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_trang)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_lon2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel8Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lb_trang))
                    .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_nho2)
                        .addComponent(btn_lon2)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Còn Hiệu Lực", jPanel8);

        jPanel9.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        tbl_KhuyenMaiHHL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "Mã khuyến mại", "Tên chương trình", "Số Lượng", "Áp dụng", "Giá Trị", "Giảm tối đa", "Ngày bắt đầu", "Ngày kết thúc", "Trạng thái"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                true, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tbl_KhuyenMaiHHL.setSelectionBackground(new java.awt.Color(153, 255, 153));
        tbl_KhuyenMaiHHL.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbl_KhuyenMaiHHLMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbl_KhuyenMaiHHL);

        btn_nho3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utility/icon/Left.png"))); // NOI18N
        btn_nho3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_nho3ActionPerformed(evt);
            }
        });

        lb_trang1.setText("jLabel9");

        btn_lon3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utility/icon/Right.png"))); // NOI18N
        btn_lon3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_lon3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 1052, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(269, 269, 269)
                .addComponent(btn_nho3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lb_trang1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btn_lon3)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel9Layout.createSequentialGroup()
                        .addGap(11, 11, 11)
                        .addComponent(lb_trang1))
                    .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btn_nho3)
                        .addComponent(btn_lon3)))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Hết Hiệu Lực", jPanel9);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 305, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel7Layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(8, 8, 8))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btnLuuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLuuActionPerformed
        //TODO add your handling code here:
        ArrayList<KhuyenMai> listKM = khuyenMaiRepository.getAll();

        // Thêm khuyến mại
        KhuyenMai km = KiemTraDuLieu();

        String makm = txtMaKhuyenMai.getText();
        for (KhuyenMai kmCheck : listKM) {
            if (makm.equals(kmCheck.getMaKhuyenMai())) {
                JOptionPane.showMessageDialog(this, "Mã đã tồn tại");
                return;
            }
        }
        if (km == null) {
            return;
        }
        if (km.getNgayKetThuc().before(new java.util.Date())) {
            JOptionPane.showMessageDialog(this, "Ngày kết thúc phải sau ngày hiện tại");
            return;
        }
        if (khuyenMaiRepository.them(km) != null) {
            JOptionPane.showMessageDialog(this, "Thêm Thành Công !!");

            loadDataTableKhuyenMaiCHL();
            lammoi();
        } else {
            JOptionPane.showMessageDialog(this, "Thêm Thất bại !!");
        }
    }//GEN-LAST:event_btnLuuActionPerformed

    private void btnSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuaActionPerformed
        // TODO add your handling code here:
        ArrayList<KhuyenMai> listKM = khuyenMaiRepository.getAll();
        int row = tbl_KhuyenMai.getSelectedRow();
        if (row < 0) {
            JOptionPane.showMessageDialog(this, "Chọn dòng cần sửa");
            return;
        }
        KhuyenMai km = KiemTraDuLieu();
        if (km == null) {
            return;
        }
        String ma = txtMaKhuyenMai.getText().trim();
        km.setMaKhuyenMai(ma);
        KhuyenMai k = new KhuyenMai();

        // set IDKM vào CTSP
        // Danh mục được chọn
        if (khuyenMaiRepository.updateKhuyenMai(km) != null) {
            JOptionPane.showMessageDialog(this, "Sửa thành công");
            loadDataTableKhuyenMaiCHL();
        } else {
            JOptionPane.showMessageDialog(this, "Sửa thất bại");
        }
        loadDataTableKhuyenMaiCHL();
        loadDataTableKhuyenMaiHHL();
        lammoi();
    }//GEN-LAST:event_btnSuaActionPerformed

    private void btn_nho2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nho2ActionPerformed
        // TODO add your handling code here:
        if (soTrang3 > 1) {
            soTrang3--;
            loadDataTableKhuyenMaiCHL();
            lb_trang.setText(soTrang3 + "/" + SoBanGhiKhuyenMaiCHL());

        }
    }//GEN-LAST:event_btn_nho2ActionPerformed

    private void btn_lon2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lon2ActionPerformed
        // TODO add your handling code here:
        if (soTrang3 < SoBanGhiKhuyenMaiCHL()) {
            soTrang3++;
            loadDataTableKhuyenMaiCHL();
            lb_trang.setText(soTrang3 + "/" + SoBanGhiKhuyenMaiCHL());
        }
    }//GEN-LAST:event_btn_lon2ActionPerformed

    private void tbl_KhuyenMaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_KhuyenMaiMouseClicked
        // TODO add your handling code here:
        int row = tbl_KhuyenMai.getSelectedRow();
        if (row < 0) {

            return;
        }
        txtMaKhuyenMai.setText(tbl_KhuyenMai.getValueAt(row, 1).toString());
        txtTenKhuyenMai.setText(tbl_KhuyenMai.getValueAt(row, 2).toString());
        txtSoLuong.setText(tbl_KhuyenMai.getValueAt(row, 3).toString());

        try {
            String ngaybd = tbl_KhuyenMai.getValueAt(row, 7).toString();
            String ngaykt = tbl_KhuyenMai.getValueAt(row, 8).toString();

            java.util.Date date = new SimpleDateFormat("yyyy-MM-dd").parse(ngaybd);
            java.util.Date date2 = new SimpleDateFormat("yyyy-MM-dd").parse(ngaykt);
            txtBatDau.setDate(date);
            txtKetThuc.setDate(date2);
        } catch (ParseException e) {
            e.printStackTrace();
        }
        txtGiaTri.setText(tbl_KhuyenMai.getValueAt(row, 5).toString());
        txtDieuKienGiam.setText(tbl_KhuyenMai.getValueAt(row, 6).toString());
        cbbHinhThucGiamGia.setSelectedItem(tbl_KhuyenMai.getValueAt(row, 4).toString());
        ArrayList<KhuyenMai> k = khuyenMaiRepository.getAll();

        String idKM = "";
        for (KhuyenMai x : k) {
            if (x.getMaKhuyenMai() != null && x.getMaKhuyenMai().equals(tbl_KhuyenMai.getValueAt(row, 0).toString())) {

                idKM = x.getId();

            }
        }
    }//GEN-LAST:event_tbl_KhuyenMaiMouseClicked

    private void btnLamMOiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLamMOiActionPerformed
        // TODO add your handling code here:
        lammoi();
    }//GEN-LAST:event_btnLamMOiActionPerformed

    private void tbl_KhuyenMaiHHLMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbl_KhuyenMaiHHLMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tbl_KhuyenMaiHHLMouseClicked

    private void btn_nho3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_nho3ActionPerformed
        // TODO add your handling code here:
        if (soTrang3 > 1) {
            soTrang3--;
            loadDataTableKhuyenMaiHHL();
            lb_trang1.setText(soTrang3 + "/" + SoBanGhiKhuyenMaiHHL());

        }
    }//GEN-LAST:event_btn_nho3ActionPerformed

    private void btn_lon3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_lon3ActionPerformed
        // TODO add your handling code here:
        if (soTrang3 < SoBanGhiKhuyenMaiHHL()) {
            soTrang3++;
            loadDataTableKhuyenMaiHHL();
            lb_trang1.setText(soTrang3 + "/" + SoBanGhiKhuyenMaiCHL());
        }
    }//GEN-LAST:event_btn_lon3ActionPerformed

    private void cbbHinhThucGiamGiaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbHinhThucGiamGiaActionPerformed
        // TODO add your handling code here:
//        if (cbbHinhThucGiamGia.getSelectedIndex()==1){
//           txtGiamToiDa.setEditable(false);
////           txtGiamToiDa.setText("");
//       } else txtGiamToiDa.setEditable(true);

    }//GEN-LAST:event_cbbHinhThucGiamGiaActionPerformed

    private void txtGiaTriCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtGiaTriCaretUpdate
        // TODO add your handling code here:
//        if (cbbHinhThucGiamGia.getSelectedIndex()==1){
//           txtGiamToiDa.setText(txtGiaTri.getText());
//       }
    }//GEN-LAST:event_txtGiaTriCaretUpdate


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLamMOi;
    private javax.swing.JButton btnLuu;
    private javax.swing.JButton btnSua;
    private javax.swing.JButton btn_lon2;
    private javax.swing.JButton btn_lon3;
    private javax.swing.JButton btn_nho2;
    private javax.swing.JButton btn_nho3;
    private javax.swing.JComboBox<String> cbbHinhThucGiamGia;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JLabel lb_trang;
    private javax.swing.JLabel lb_trang1;
    private javax.swing.JTable tbl_KhuyenMai;
    private javax.swing.JTable tbl_KhuyenMaiHHL;
    private com.toedter.calendar.JDateChooser txtBatDau;
    private javax.swing.JTextField txtDieuKienGiam;
    private javax.swing.JTextField txtGiaTri;
    private com.toedter.calendar.JDateChooser txtKetThuc;
    private javax.swing.JTextField txtMaKhuyenMai;
    private javax.swing.JTextField txtSoLuong;
    private javax.swing.JTextField txtTenKhuyenMai;
    // End of variables declaration//GEN-END:variables
}
