/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import java.awt.Color;
import java.awt.LayoutManager;
import java.awt.Panel;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author LENOVO
 */
public class TrangChu extends javax.swing.JFrame {

    /**
     * Creates new form TrangChu
     */
    model.NhanVien nv = Login.nvs;

    private JPanel panel;

    public TrangChu() {
        initComponents();
        setLocationRelativeTo(null);
        lblNhanVien.setText(nv.getHoVaTen());
        phanQuyen();
    }

    public TrangChu(JPanel panel) {
        setPanel(panel);
    }

    private void setPanel(JPanel jp) {
        jplConten.removeAll();
        jplConten.add(jp);
        jplConten.updateUI();
    }
    public void phanQuyen(){
        if(nv.getIdCV().getMaChucVu().equals("CV002")){
            btnThongke.setVisible(false);
            btnKhuyenmai.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        btnTrangchu = new javax.swing.JButton();
        btnKhachhang = new javax.swing.JButton();
        btnNhanvien = new javax.swing.JButton();
        btnKhuyenmai = new javax.swing.JButton();
        btnSanpham = new javax.swing.JButton();
        btnBanhang = new javax.swing.JButton();
        btnThongke = new javax.swing.JButton();
        btnHoadon = new javax.swing.JButton();
        btnThoat = new javax.swing.JButton();
        btnThongke1 = new javax.swing.JButton();
        jplConten = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lblNhanVien = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel2.setBackground(new java.awt.Color(224, 235, 249));
        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        btnTrangchu.setBackground(new java.awt.Color(204, 204, 204));
        btnTrangchu.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utility/icon/iconHome.png"))); // NOI18N
        btnTrangchu.setText("Trang chủ ");
        btnTrangchu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnTrangchuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnTrangchuMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnTrangchuMouseExited(evt);
            }
        });
        btnTrangchu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTrangchuActionPerformed(evt);
            }
        });

        btnKhachhang.setBackground(new java.awt.Color(204, 204, 204));
        btnKhachhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utility/icon/add-user.png"))); // NOI18N
        btnKhachhang.setText("Khách hàng ");
        btnKhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKhachhangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnKhachhangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnKhachhangMouseExited(evt);
            }
        });
        btnKhachhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKhachhangActionPerformed(evt);
            }
        });

        btnNhanvien.setBackground(new java.awt.Color(204, 204, 204));
        btnNhanvien.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utility/icon/employees.png"))); // NOI18N
        btnNhanvien.setText("Nhân viên ");
        btnNhanvien.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnNhanvienMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnNhanvienMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnNhanvienMouseExited(evt);
            }
        });
        btnNhanvien.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                btnNhanvienComponentShown(evt);
            }
        });
        btnNhanvien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNhanvienActionPerformed(evt);
            }
        });

        btnKhuyenmai.setBackground(new java.awt.Color(204, 204, 204));
        btnKhuyenmai.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utility/icon/coupon.png"))); // NOI18N
        btnKhuyenmai.setText("Khuyến mại ");
        btnKhuyenmai.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnKhuyenmaiMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnKhuyenmaiMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnKhuyenmaiMouseExited(evt);
            }
        });

        btnSanpham.setBackground(new java.awt.Color(204, 204, 204));
        btnSanpham.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utility/icon/box.png"))); // NOI18N
        btnSanpham.setText("Sản phẩm");
        btnSanpham.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnSanphamMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnSanphamMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnSanphamMouseExited(evt);
            }
        });

        btnBanhang.setBackground(new java.awt.Color(204, 204, 204));
        btnBanhang.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utility/icon/banHang.png"))); // NOI18N
        btnBanhang.setText("Bán hàng ");
        btnBanhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnBanhangMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnBanhangMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnBanhangMouseExited(evt);
            }
        });
        btnBanhang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBanhangActionPerformed(evt);
            }
        });

        btnThongke.setBackground(new java.awt.Color(204, 204, 204));
        btnThongke.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utility/icon/iconDT.png"))); // NOI18N
        btnThongke.setText("Thống kê ");
        btnThongke.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThongkeMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThongkeMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThongkeMouseExited(evt);
            }
        });
        btnThongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongkeActionPerformed(evt);
            }
        });

        btnHoadon.setBackground(new java.awt.Color(204, 204, 204));
        btnHoadon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utility/icon/import.png"))); // NOI18N
        btnHoadon.setText("Hóa đơn ");
        btnHoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnHoadonMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnHoadonMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnHoadonMouseExited(evt);
            }
        });
        btnHoadon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnHoadonActionPerformed(evt);
            }
        });

        btnThoat.setBackground(new java.awt.Color(204, 204, 204));
        btnThoat.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utility/icon/logout.png"))); // NOI18N
        btnThoat.setText("Thoát");
        btnThoat.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThoatMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThoatMouseExited(evt);
            }
        });
        btnThoat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThoatActionPerformed(evt);
            }
        });

        btnThongke1.setBackground(new java.awt.Color(204, 204, 204));
        btnThongke1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/utility/icon/Refresh.png"))); // NOI18N
        btnThongke1.setText("Trả Hàng");
        btnThongke1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnThongke1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnThongke1MouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                btnThongke1MouseExited(evt);
            }
        });
        btnThongke1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThongke1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(32, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(btnThoat, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnTrangchu, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 136, Short.MAX_VALUE)
                    .addComponent(btnKhuyenmai, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnSanpham, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBanhang, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThongke, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHoadon, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnNhanvien, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnKhachhang, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnThongke1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(28, 28, 28))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {btnBanhang, btnHoadon, btnKhuyenmai, btnSanpham, btnThoat, btnThongke, btnThongke1, btnTrangchu});

        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(btnTrangchu, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnKhachhang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnNhanvien, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnKhuyenmai, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnSanpham, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28)
                .addComponent(btnBanhang, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHoadon, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addComponent(btnThongke, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(33, 33, 33)
                .addComponent(btnThongke1, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26)
                .addComponent(btnThoat, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2Layout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {btnBanhang, btnHoadon, btnKhuyenmai, btnSanpham, btnThoat, btnThongke, btnTrangchu});

        jplConten.setBackground(new java.awt.Color(255, 255, 255));
        jplConten.setLayout(new java.awt.GridLayout(0, 1));

        jPanel1.setBackground(new java.awt.Color(224, 235, 249));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.setPreferredSize(new java.awt.Dimension(900, 90));

        jLabel1.setText("Ảnh ");

        lblNhanVien.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNhanVien.setText("Phạm Minh Quân ");

        jLabel3.setText("Đăng xuất ");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Sneaker Poly ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(lblNhanVien)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 634, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(19, 19, 19))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(lblNhanVien)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 948, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jplConten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jplConten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnNhanvienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNhanvienActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNhanvienActionPerformed

    private void btnThoatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThoatActionPerformed
        int confirmed = JOptionPane.showConfirmDialog(this, "Bạn có chắc muốn thoát chứ ?", "Xác nhận thoát", JOptionPane.YES_NO_OPTION);

        if (confirmed == JOptionPane.YES_OPTION) {
            System.exit(0);
        }
    }//GEN-LAST:event_btnThoatActionPerformed

    private void btnHoadonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnHoadonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnHoadonActionPerformed

    private void btnTrangchuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTrangchuActionPerformed


    }//GEN-LAST:event_btnTrangchuActionPerformed

    private void btnTrangchuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrangchuMouseClicked
        panel = new jplTrangChu();
        setPanel(panel);
    }//GEN-LAST:event_btnTrangchuMouseClicked

    private void btnKhachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhachhangMouseClicked
        try {
            panel = new jplKhachHang();
        } catch (Exception ex) {
            Logger.getLogger(TrangChu.class.getName()).log(Level.SEVERE, null, ex);
        }
        setPanel(panel);
    }//GEN-LAST:event_btnKhachhangMouseClicked

    private void btnNhanvienComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_btnNhanvienComponentShown
        // TODO add your handling code here:
    }//GEN-LAST:event_btnNhanvienComponentShown

    private void btnSanphamMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSanphamMouseClicked
        panel = new jplSanPham();
        setPanel(panel);
    }//GEN-LAST:event_btnSanphamMouseClicked

    private void btnTrangchuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrangchuMouseEntered
        btnTrangchu.setBackground(Color.ORANGE);
    }//GEN-LAST:event_btnTrangchuMouseEntered

    private void btnTrangchuMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnTrangchuMouseExited
        btnTrangchu.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnTrangchuMouseExited

    private void btnKhachhangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhachhangMouseEntered
        btnKhachhang.setBackground(Color.ORANGE);
    }//GEN-LAST:event_btnKhachhangMouseEntered

    private void btnKhachhangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhachhangMouseExited
        btnKhachhang.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnKhachhangMouseExited

    private void btnNhanvienMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanvienMouseEntered
        btnNhanvien.setBackground(Color.ORANGE);
    }//GEN-LAST:event_btnNhanvienMouseEntered

    private void btnNhanvienMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanvienMouseExited
        btnNhanvien.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnNhanvienMouseExited

    private void btnSanphamMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSanphamMouseEntered
        btnSanpham.setBackground(Color.ORANGE);
    }//GEN-LAST:event_btnSanphamMouseEntered

    private void btnSanphamMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnSanphamMouseExited
        btnSanpham.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnSanphamMouseExited

    private void btnBanhangMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBanhangMouseEntered
        btnBanhang.setBackground(Color.ORANGE);
    }//GEN-LAST:event_btnBanhangMouseEntered

    private void btnBanhangMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBanhangMouseExited
        btnBanhang.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnBanhangMouseExited

    private void btnThongkeMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongkeMouseEntered
        btnThongke.setBackground(Color.ORANGE);
    }//GEN-LAST:event_btnThongkeMouseEntered

    private void btnThongkeMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongkeMouseExited
        btnThongke.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnThongkeMouseExited

    private void btnHoadonMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHoadonMouseEntered
        btnHoadon.setBackground(Color.ORANGE);
    }//GEN-LAST:event_btnHoadonMouseEntered

    private void btnHoadonMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHoadonMouseExited
        btnHoadon.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnHoadonMouseExited

    private void btnThoatMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseEntered
        btnThoat.setBackground(Color.ORANGE);
    }//GEN-LAST:event_btnThoatMouseEntered

    private void btnThoatMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThoatMouseExited
        btnThoat.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnThoatMouseExited

    private void btnKhuyenmaiMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhuyenmaiMouseEntered
        btnKhuyenmai.setBackground(Color.ORANGE);
    }//GEN-LAST:event_btnKhuyenmaiMouseEntered

    private void btnKhuyenmaiMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhuyenmaiMouseExited
        btnKhuyenmai.setBackground(Color.lightGray);
    }//GEN-LAST:event_btnKhuyenmaiMouseExited

    private void btnKhachhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKhachhangActionPerformed

    }//GEN-LAST:event_btnKhachhangActionPerformed

    private void btnNhanvienMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnNhanvienMouseClicked
        panel = new jplNhanVien();
        setPanel(panel);
    }//GEN-LAST:event_btnNhanvienMouseClicked

    private void btnKhuyenmaiMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnKhuyenmaiMouseClicked
        try {
            panel = new jplKhuyenMai();
        } catch (Exception ex) {
            Logger.getLogger(TrangChu.class.getName()).log(Level.SEVERE, null, ex);
        }

        setPanel(panel);
    }//GEN-LAST:event_btnKhuyenmaiMouseClicked

    private void btnThongkeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongkeMouseClicked
        panel = new jplThongKe();
        setPanel(panel);
    }//GEN-LAST:event_btnThongkeMouseClicked

    private void btnHoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnHoadonMouseClicked
        panel = new jplHoaDon();
        setPanel(panel);
    }//GEN-LAST:event_btnHoadonMouseClicked

    private void btnBanhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnBanhangMouseClicked
        panel = new jplBanHang();
        setPanel(panel);
    }//GEN-LAST:event_btnBanhangMouseClicked

    private void btnBanhangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBanhangActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBanhangActionPerformed

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        int choice = JOptionPane.showConfirmDialog(this, "Bạn có muốn đăng xuất không", "Đăng xuất", JOptionPane.YES_NO_OPTION, JOptionPane.INFORMATION_MESSAGE);
        if (choice == JOptionPane.YES_OPTION) {
            this.dispose();
            new Login().setVisible(true);
        } else {
            JOptionPane.showMessageDialog(this, "Hủy đăng xuất");
        }
    }//GEN-LAST:event_jLabel3MouseClicked

    private void btnThongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongkeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThongkeActionPerformed

    private void btnThongke1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongke1MouseClicked
        panel = new jplTraHang1();
        setPanel(panel);
    }//GEN-LAST:event_btnThongke1MouseClicked

    private void btnThongke1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongke1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThongke1MouseEntered

    private void btnThongke1MouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnThongke1MouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThongke1MouseExited

    private void btnThongke1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThongke1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnThongke1ActionPerformed

    /**
     * @param args the command line arguments
     */
////    public static void main(String args[]) {
////        java.awt.EventQueue.invokeLater(new Runnable() {
////            public void run() {
////                new TrangChu().setVisible(true);
////            }
////        });
//        
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBanhang;
    private javax.swing.JButton btnHoadon;
    private javax.swing.JButton btnKhachhang;
    private javax.swing.JButton btnKhuyenmai;
    private javax.swing.JButton btnNhanvien;
    private javax.swing.JButton btnSanpham;
    private javax.swing.JButton btnThoat;
    private javax.swing.JButton btnThongke;
    private javax.swing.JButton btnThongke1;
    private javax.swing.JButton btnTrangchu;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jplConten;
    private javax.swing.JLabel lblNhanVien;
    // End of variables declaration//GEN-END:variables

}
